import type { Country } from './game'

// ISO 3166-1 alpha-2 code (lowercase, must exist on flagcdn.com) + display name.
// Add a country = add an entry here.
export const countries: Country[] = [
    { code: 'de', name: 'Germany' },
    { code: 'fr', name: 'France' },
    { code: 'it', name: 'Italy' },
    { code: 'es', name: 'Spain' },
    { code: 'gb', name: 'United Kingdom' },
    { code: 'nl', name: 'Netherlands' },
    { code: 'be', name: 'Belgium' },
    { code: 'at', name: 'Austria' },
    { code: 'ch', name: 'Switzerland' },
    { code: 'pl', name: 'Poland' },
    { code: 'se', name: 'Sweden' },
    { code: 'no', name: 'Norway' },
    { code: 'dk', name: 'Denmark' },
    { code: 'fi', name: 'Finland' },
    { code: 'pt', name: 'Portugal' },
    { code: 'gr', name: 'Greece' },
    { code: 'cz', name: 'Czech Republic' },
    { code: 'hu', name: 'Hungary' },
    { code: 'ie', name: 'Ireland' },
    { code: 'ro', name: 'Romania' },
    { code: 'jp', name: 'Japan' },
    { code: 'kr', name: 'South Korea' },
    { code: 'cn', name: 'China' },
    { code: 'in', name: 'India' },
    { code: 'au', name: 'Australia' },
    { code: 'nz', name: 'New Zealand' },
    { code: 'ca', name: 'Canada' },
    { code: 'us', name: 'United States' },
    { code: 'mx', name: 'Mexico' },
    { code: 'br', name: 'Brazil' },
    { code: 'ar', name: 'Argentina' },
    { code: 'cl', name: 'Chile' },
    { code: 'za', name: 'South Africa' },
    { code: 'eg', name: 'Egypt' },
    { code: 'ng', name: 'Nigeria' },
    { code: 'ke', name: 'Kenya' },
    { code: 'tr', name: 'Turkey' },
    { code: 'ru', name: 'Russia' },
    { code: 'ua', name: 'Ukraine' },
    { code: 'il', name: 'Israel' },
    { code: 'sa', name: 'Saudi Arabia' },
    { code: 'ae', name: 'United Arab Emirates' },
    { code: 'th', name: 'Thailand' },
    { code: 'vn', name: 'Vietnam' },
    { code: 'id', name: 'Indonesia' },
    { code: 'my', name: 'Malaysia' },
    { code: 'sg', name: 'Singapore' },
    { code: 'ph', name: 'Philippines' },
    { code: 'bg', name: 'Bulgaria' },
    { code: 'hr', name: 'Croatia' },
    { code: 'sk', name: 'Slovakia' },
    { code: 'si', name: 'Slovenia' },
    { code: 'ee', name: 'Estonia' },
    { code: 'lv', name: 'Latvia' },
    { code: 'lt', name: 'Lithuania' },
    { code: 'is', name: 'Iceland' },
    { code: 'lu', name: 'Luxembourg' },
    { code: 'mt', name: 'Malta' },
    { code: 'cy', name: 'Cyprus' },
    { code: 'pk', name: 'Pakistan' },
    { code: 'bd', name: 'Bangladesh' },
    { code: 'np', name: 'Nepal' },
    { code: 'lk', name: 'Sri Lanka' },
    { code: 'mm', name: 'Myanmar' },
    { code: 'kh', name: 'Cambodia' },
    { code: 'la', name: 'Laos' },
    { code: 'mn', name: 'Mongolia' },
    { code: 'kp', name: 'North Korea' },
    { code: 'tw', name: 'Taiwan' },
    { code: 'hk', name: 'Hong Kong' },
    { code: 'mo', name: 'Macau' },
    { code: 'qa', name: 'Qatar' },
    { code: 'kw', name: 'Kuwait' },
    { code: 'bh', name: 'Bahrain' },
    { code: 'om', name: 'Oman' },
    { code: 'ye', name: 'Yemen' },
    { code: 'jo', name: 'Jordan' },
    { code: 'lb', name: 'Lebanon' },
    { code: 'sy', name: 'Syria' },
    { code: 'iq', name: 'Iraq' },
    { code: 'ir', name: 'Iran' },
    { code: 'af', name: 'Afghanistan' },
    { code: 'uz', name: 'Uzbekistan' },
    { code: 'kz', name: 'Kazakhstan' },
    { code: 'tm', name: 'Turkmenistan' },
    { code: 'kg', name: 'Kyrgyzstan' },
    { code: 'tj', name: 'Tajikistan' },
    { code: 'az', name: 'Azerbaijan' },
    { code: 'ge', name: 'Georgia' },
    { code: 'am', name: 'Armenia' },
    { code: 'ma', name: 'Morocco' },
    { code: 'dz', name: 'Algeria' },
    { code: 'tn', name: 'Tunisia' },
    { code: 'ly', name: 'Libya' },
    { code: 'sd', name: 'Sudan' },
    { code: 'et', name: 'Ethiopia' },
    { code: 'tz', name: 'Tanzania' },
    { code: 'ug', name: 'Uganda' },
    { code: 'rw', name: 'Rwanda' },
    { code: 'gh', name: 'Ghana' },
    { code: 'ci', name: 'Ivory Coast' },
    { code: 'sn', name: 'Senegal' },
    { code: 'cm', name: 'Cameroon' },
    { code: 'ao', name: 'Angola' },
    { code: 'zw', name: 'Zimbabwe' },
    { code: 'bw', name: 'Botswana' },
    { code: 'na', name: 'Namibia' },
    { code: 'mz', name: 'Mozambique' },
    { code: 'mg', name: 'Madagascar' },
    { code: 'co', name: 'Colombia' },
    { code: 've', name: 'Venezuela' },
    { code: 'pe', name: 'Peru' },
    { code: 'ec', name: 'Ecuador' },
    { code: 'bo', name: 'Bolivia' },
    { code: 'py', name: 'Paraguay' },
    { code: 'uy', name: 'Uruguay' },
    { code: 'gy', name: 'Guyana' },
    { code: 'sr', name: 'Suriname' },
    { code: 'pa', name: 'Panama' },
    { code: 'cr', name: 'Costa Rica' },
    { code: 'ni', name: 'Nicaragua' },
    { code: 'hn', name: 'Honduras' },
    { code: 'sv', name: 'El Salvador' },
    { code: 'gt', name: 'Guatemala' },
    { code: 'bz', name: 'Belize' },
    { code: 'cu', name: 'Cuba' },
    { code: 'jm', name: 'Jamaica' },
    { code: 'ht', name: 'Haiti' },
    { code: 'do', name: 'Dominican Republic' },
    { code: 'pr', name: 'Puerto Rico' },
    { code: 'bs', name: 'Bahamas' },
    { code: 'tt', name: 'Trinidad and Tobago' },
    { code: 'bb', name: 'Barbados' },
]
